repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
- repo: local
  hooks:
    - id: trk-validate
      name: TRK schema validation
      entry: python scripts/validate.py
      language: system
      pass_filenames: false
